<?xml version="1.0" ?>
<robot name="hbot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="inertials.xacro" />
  <xacro:include filename="materials.xacro" />

  <!-- Define some constants -->
  <xacro:property name="base_width" value="0.14"/>
  <xacro:property name="base_height" value="0.08"/>
  <xacro:property name="base_length" value="0.17"/>

  <xacro:property name="wheel_radius" value="0.0325"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="wheel_ygap" value="0.035"/>
  <xacro:property name="wheel_zoff" value="0.05"/>
  <xacro:property name="wheel_xoff" value="0.05"/>

  <xacro:property name="caster_radius" value="0.01"/>
  <xacro:property name="caster_xoff" value="0.07"/>

  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:solid_cuboid_inertial
      rpy="0 0 0" xyz="0 0 0" mass="0.5"
      x="${base_length}" y="${base_width}" z="${base_height}"
    />
  </link>

  <!-- Wheel -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
          <cylinder radius="0.005" length="0.01">
            <origin xyz="0 0 ${wheel_width/2+0.005}" rpy="0 0 0"/>
          </cylinder>
        </geometry>
        <material name="Black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:solid_cylinder_inertial
        rpy="0 0 0"
        xyz="0 0 0"
        mass="0.1"
        radius="${wheel_radius}"
        length="${wheel_width}"
      />
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="left_wheel" x_reflect="-1" y_reflect="1"/>
  <xacro:wheel prefix="right_wheel" x_reflect="-1" y_reflect="-1"/>

  <!-- Caster -->
  <link name="front_caster">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <xacro:null_inertial/>
  </link>

  <joint name="front_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_xoff} 0.0 ${-wheel_zoff-wheel_radius+caster_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Lidar -->
  <link name="laser">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.025"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.03" length="0.025"/>
      </geometry>
    </collision>
    <xacro:null_inertial/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="0 0 ${base_height/2+0.015}" rpy="0 0 0"/>
  </joint>
</robot>
